layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Django
    image_url: https://cdn.iconscout.com/icon/free/png-256/django-13-1175187.png
    
  - name: Node-JS
    image_url: https://pluralsight.imgix.net/paths/path-icons/nodejs-601628d09d.png
    
  - name: Blockchain
    image_url: https://image.flaticon.com/icons/svg/824/824918.svg

  
projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: hrishabh.sharma.33
  linkedin: hrishabh-sharma-122338163/
  medium: hrishabh01sharma
  twitter: Hrishab46986230
  # youtube: your_username

